init_widget = "List"
window_title = "todo"
#layout = """
#[
#  Direction: Horizontal,
#  Size: 50%,
#  [
#    List: 80%,
#    Preview: 20%
#  ],
#  [
#    Direction: Vertical,
#    Done: 60%,
#    [
#      Contexts: 50%,
#      Projects: 50%,
#    ],
#  ],
#]
#"""
layout = """
[
  List: 80%,
  Preview: 20%
]
"""
paste_behavior = "Insert"
enable_mouse = true
use_done = false
pending_sort = "None"
done_sort = "None"
delete_final_date = true
set_final_date = "OnlyMissing"
set_created_date = true
todo_path = "/home/mike/todo.txt"
file_watcher = true
save_policy = "OnChange"
border_type = "Rounded"
list_shift = 4
pending_format = "[$subject](! priority)"
done_format = "[$subject](! priority)"
preview_format = """
Pending: $pending Done: $done
Subject: $subject
Priority: $priority
Create date: $create_date
Link: $link"""
wrap_preview = true
active_color = "Red"

[window_keybinds]
u = "Load"
"Shift+k" = "MoveUp"
"Shift+e" = "EditMode"
"Shift+s" = "Save"
"Shift+h" = "MoveLeft"
"Shift+l" = "MoveRight"
"Shift+j" = "MoveDown"
"Shift+i" = "InsertMode"
"/" = "SearchMode"
q = "Quit"

[list_refresh_rate]
secs = 5
nanos = 0

[autosave_duration]
secs = 900
nanos = 0

[tasks_keybind]
"Shift+u" = "SwapUpItem"
Enter = "Select"
n = "NextSearch"
d = "MoveItem"
"Shift+d" = "SwapDownItem"
"Shift+n" = "PrevSearch"
x = "RemoveItem"

[category_keybind]
Enter = "Select"
Backspace = "Remove"
"Shift+n" = "PrevSearch"
n = "NextSearch"

[list_keybind]
k = "ListUp"
g = "ListFirst"
"Shift+g" = "ListLast"
h = "CleanSearch"
j = "ListDown"

[list_active_color]
bg = "#333333"
fg = "#ffffff"

[pending_active_color]

[done_active_color]

[category_active_color]

[projects_active_color]

[contexts_active_color]

[tags_active_color]

[priority_style.B]
fg = "Yellow"

[priority_style.C]
fg = "Blue"

[priority_style.A]
fg = "Red"

[projects_style]
fg = "Yellow"

[contexts_style]
fg = "Green"

[hashtags_style]

[category_style]

[category_select_style]
fg = "Green"

[category_remove_style]
fg = "Red"

[custom_category_style."+todo-tui"]
fg = "LightBlue"

[highlight]
bg = "Yellow"
